### PR TITLE
Allow filename with non ascii characters

### LINKED ISSUE #32: Non ascii characters not supported in filename
Hi,
The way header is set for filename doesn't support non ascii characters.

The following line manually adds an header :
- https://github.com/Kozea/Flask-WeasyPrint/blob/b3182cd11600ca9bcf7017ab11f7d527e23721be/flask_weasyprint/__init__.py#L201

However, this line doesn't rely on flask which provides a way of returning filename containing utf-8 characters.
- https://stackoverflow.com/questions/43365640/set-unicode-filename-in-flask-response-header

Maybe we could use flask base code instead of manually adding this header ?
Thanks

### PR DESCRIPTION
**Pull request by Ph0tonic**
Fixes #32

### CODE REVIEW

**Comment by liZe** [comment]
Thanks for the PR! Could you please rebase your branch on main so that unrelated bugs are fixed? Thanks.

**Comment by Ph0tonic** [comment]
Here it is :+1:

**Comment by liZe** [comment]
Thanks!

Looks like there are some problems, at least to handle the case when there’s no explicit filename given. Do you want to fix the problem, or do you prefer if I try to find a solution?

**Comment by liZe** [comment]
Thanks! I’ve updated tests and cleaned a couple of lines.

**Pull request merged**
